title="example title"

date="today"

[sus.mogus]
"maslo"=1000
'wink'=true
yo=-60
hey="bhlah\""
binary = 0b10_1
octal = 0o20_25
hex= 0xDEAD_BEEF

[sus.glombus] # some comment
'quoted "value"' = "test"
"bingus.bus" = "abc"
"bingus.gus" = "what am i doing here"
"bingus.gus.furtherus" = "It works somehow."